# serverless.yml

service: apollo-lambda
provider:
  name: aws
  runtime: nodejs8.10
  region: ap-southeast-2
  stage: production
functions:
  graphql:
    # this is formatted as <FILENAME>.<HANDLER>
    handler: index.handler
    events:
    - http:
        path: graphql
        method: post
        cors: true
    - http:
        path: graphql
        method: get
        cors: true
